version: "3.8"

services:

  sonarqube:
    image: sonarqube:10.3.0-community
    container_name: sonarqube
    ports:
      - 9000:9000
    environment:
      SONAR_WEB_HOST: 0.0.0.0
      SONAR_WEB_PORT: 9000
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONAR_JDBC_USERNAME: postgres
      SONAR_JDBC_PASSWORD: abcd1234
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    depends_on:
      postgres:
        condition: service_healthy


volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs: