keycloak:
  realm: ${KEYCLOAK_REALM:hfs-realm}
  host: ${KEYCLOAK_HOST:http://localhost:8080}

postgresql:
  username: ${DATABASE_POSTGRESQL_USERNAME:postgres}
  password: ${DATABASE_POSTGRESQL_PASSWORD:abcd1234}
  schema: public
  url: ${DATABASE_POSTGRESQL_URL:localhost:5434}

#mysql:
#  username: ${DATABASE_MYSQL_USERNAME:root}
#  password: ${DATABASE_MYSQL_PASSWORD:abcd1234}
#  schema: public
#  url: ${DATABASE_MYSQL_URL:localhost:3306}

#spring:
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration
#      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration