version: "3.8"

services:
  
  prometheus:
    image: prom/prometheus:v2.45.3
    container_name: prometheus
    ports:
      - 5000:9090
    volumes: 
      - prometheus:/prometheus 
      - ../infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:10.3.1
    container_name: grafana
    ports:
      - 3000:3000
    environment: 
      - PROMETHEUS_URL=http://prometheus:9090
      - DS_PROMETHEUS=prometheus
    volumes:
      - ../infra/grafana/config.ini:/etc/grafana/config.ini
      - ../infra/grafana/provisioning:/etc/grafana/provisioning
      - ../infra/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

volumes:
  prometheus: